// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyCode } from "./KeyCode";
import type { KeyModifiers } from "./KeyModifiers";
import type { ScrollDirection } from "./ScrollDirection";

/**
 * Messages sent from client to server
 */
export type ClientMessage = { "type": "key", code: KeyCode, modifiers: KeyModifiers, } | { "type": "resize", rows: number, cols: number, } | { "type": "scroll", direction: ScrollDirection, lines: number, };
