// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridCell } from "./GridCell";
import type { SerializablePtySize } from "./SerializablePtySize";

/**
 * Terminal grid update messages
 */
export type GridUpdateMessage = { "Keyframe": { size: SerializablePtySize, cells: Array<[[number, number], GridCell]>, cursor: [number, number], cursor_visible: boolean, scrollback_position: number, scrollback_total: number, timestamp: string, } } | { "Diff": { changes: Array<[number, number, GridCell]>, cursor: [number, number] | null, cursor_visible: boolean | null, scrollback_position: number | null, scrollback_total: number | null, timestamp: string, } };
