// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalColor } from "./TerminalColor";

/**
 * Terminal grid cell representation
 */
export type GridCell = { char: string, fg_color?: TerminalColor | null, bg_color?: TerminalColor | null, bold?: boolean, italic?: boolean, underline?: boolean, reverse?: boolean, };
