// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonApiResourceIdentifier } from "./JsonApiResourceIdentifier";

/**
 * JSON API relationship - supports both to-one and to-many relationships
 */
export type JsonApiRelationship = { data: JsonApiResourceIdentifier, } | { data: Array<JsonApiResourceIdentifier>, };
