// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonApiError } from "./JsonApiError";

/**
 * JSON API error document
 */
export type JsonApiErrorDocument = { errors: Array<JsonApiError>, };
