// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonApiRelationship } from "./JsonApiRelationship";

/**
 * JSON API resource object
 */
export type JsonApiResource<T> = { type: string, id: string, attributes: T | null, relationships: { [key in string]?: JsonApiRelationship } | null, };
