// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * JSON API success document with data
 */
export type JsonApiDocument<T> = { data: T, };
