// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * JSON API error object
 */
export type JsonApiError = { status: string | null, title: string | null, detail: string | null, };
