// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Key codes that can be sent to terminal
 */
export type KeyCode = { "Char": string } | "Backspace" | "Enter" | "Left" | "Right" | "Up" | "Down" | "Home" | "End" | "PageUp" | "PageDown" | "Tab" | "Delete" | "Insert" | { "F": number } | "Esc";
