// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyCode } from "./KeyCode";
import type { KeyModifiers } from "./KeyModifiers";

/**
 * Key event structure
 */
export type KeyEvent = { code: KeyCode, modifiers: KeyModifiers, };
