// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Key event modifiers
 */
export type KeyModifiers = { shift: boolean, ctrl: boolean, alt: boolean, meta: boolean, };
