// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionResourceTS } from "./SessionResourceTS";

export type ProjectRelationships = { recent_sessions?: Array<SessionResourceTS> | null, };
