// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionInfo } from "./SessionInfo";

export type ProjectWithSessions = { id: string, name: string, path: string, sessions: Array<SessionInfo>, };
