// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectAttributes } from "./ProjectAttributes";
import type { ProjectRelationships } from "./ProjectRelationships";

export type ProjectResourceTS = { type: string, id: string, attributes: ProjectAttributes | null, relationships?: ProjectRelationships | null, };
