// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectResourceTS } from "./ProjectResourceTS";

export type ProjectListResponse = { data: Array<ProjectResourceTS>, };
