// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridCell } from "./GridCell";
import type { SerializablePtySize } from "./SerializablePtySize";

/**
 * Messages sent from server to client - flattened to match frontend expectations
 */
export type ServerMessage = { "type": "output", data: Array<number>, timestamp: string, } | { "type": "grid_update", } & ({ "Keyframe": { size: SerializablePtySize, cells: Array<[[number, number], GridCell]>, cursor: [number, number], cursor_visible: boolean, timestamp: string, } } | { "Diff": { changes: Array<[number, number, GridCell]>, cursor: [number, number] | null, cursor_visible: boolean | null, timestamp: string, } }) | { "type": "pty_size", rows: number, cols: number, } | { "type": "error", message: string, };
