// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionAttributes } from "./SessionAttributes";

export type SessionResourceTS = { type: string, id: string, attributes: SessionAttributes | null, };
