// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionType } from "./SessionType";

export type SessionInfo = { id: string, agent: string, project: string | null, status: string, session_type: SessionType, };
