// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalColor = "Default" | { "Indexed": number } | { "Palette": number } | { "Rgb": { r: number, g: number, b: number, } };
